const quotes = [
  "Two years ago we had 50 million people subscribed to music streaming services around the world. Today we have 400 million.",
  "I spoke to Dave Chapelle for two hours this morning. He is our modern day Socrates",
  "Sometimes I push the door close button on people running towards the elevator. I just need my own elevator sometimes. My sanctuary.",
  "George Bush doesn't care about black people",
  "I need an army of angels to cover me while I pull this sword out of the stone",
  "I feel like me and Taylor might still have sex",
  "We have to evolve",
  "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle",
  "I feel like I'm too busy writing history to read it.",
  "I care. I care about everything. Sometimes not giving a f#%k is caring the most.",
  "I've known my mom since I was zero years old. She is quite dope.",
  "The world needs more Joy... this idea is super fresh",
  "I feel calm but energized",
  "Distraction is the enemy of vision",
  "The media tries to kill our heroes one at a time",
  "Have you ever thought you were in love with someone but then realized you were just staring in a mirror for 20 minutes?",
  "Speak God's truth to power",
  "Fur pillows are hard to actually sleep on",
  "I don't expect to be understood at all.",
  "We must form a union. We must unify",
  "I am one of the most famous people on the planet",
  "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.",
  "My dad got me a drone for Christmas",
  "Trust me ... I won't stop",
  "Everything you do in life stems from either fear or love",
  "All the musicians will be free",
  "Keep squares out yo circle",
  "Ma$e is one of my favorite rappers and I based a lot of my flows off of him",
  "I honestly need all my Royeres to be museum quality... if I see a fake Royere Ima have to Rick James your couch",
  "I am Warhol. I am the No. 1 most impactful artist of our generation. I am Shakespeare in the flesh.",
  "There are people sleeping in parking lots",
  "I channel Will Ferrell when I'm at the daddy daughter dances",
  "We will cure hunger",
  "I give up drinking every week",
  "My greatest award is what I'm about to do.",
  "I leave my emojis bart Simpson color",
  "Manga all day",
  "I love UZI. I be saying the same thing about Steve Jobs. I be feeling just like UZI",
  "You basically can say anything to someone on an email or text as long as you put LOL at the end.",
  "I am running for President of the United States",
  "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? Cause think of all the people that you will please if you try.",
  "I make awesome decisions in bike stores!!!",
  "We are here to complete the revolution. We are building the future",
  "You can't look at a glass half full or empty if it's overflowing.",
  "Believe in your flyness...conquer your shyness.",
  "All you have to be is yourself",
  "We all self-conscious. I'm just the first to admit it.",
  "One of my favorite of many things about what the Trump hat represents to me is that people can't tell me what to do because I'm black"
];
module.exports = quotes;