name: GitHub-Profile-3D-Contrib

on:
  schedule:
     - cron: "*/5 * * * *" # 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTING_JSON: custom-contrib.json
          USERNAME: amylovelace
      - name: Fetch Kanye quote and write to log.txt
        run: |
          echo "Fetching Kanye quote..."
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install node-fetch@2
          echo "const fetch = require('node-fetch');
          const fs = require('fs');
          fetch('https://api.kanye.rest')
            .then(res => res.json())
            .then(data => {
              fs.appendFileSync('log.txt', data.quote);
              console.log('Quote written to log.txt:', data.quote);
            });" > fetch-kanye.js
          node fetch-kanye.js
      - name: Commit & Push
        run: |
          git config user.name "AmyLovelace"
          git config user.email "amanecer.luz.cabrera@gmail.com"
          git checkout main
          git pull --rebase origin main
          git add log.txt
          git commit -m "generated $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
    
