name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTING_JSON: custom-contrib.json
          USERNAME: amylovelace

      - name: Overwrite log.txt with new timestamp
        run: |
            echo "Fetching Kanye quote..."
            node -e "import('node-fetch').then(({default:fetch}) => fetch('https://api.kanye.rest').then(r => r.json()).then(data => require('fs').writeFileSync('log.txt', `[${new Date().toISOString()}] ${data.quote}`)))"
      - name: Commit & Push
        run: |
          git config user.name AmyLovelace
          git config user.email amanecer.luz.cabrera@gmail.com
          git checkout main  # Asegúrate de que sea tu rama por defecto
          git add log.txt
          git commit -m "generated $(date -u +'%Y-%m-%d')"
          git push
